# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5844f3e3a7455bf13dad088fa80a2badbea613800ade934521cb5ed28d873ea8da0ba0ee7d435efb6eef470c7431d24356d2f7f6c3c0c6f15b117bce61a3ee9e

test:
  secret_key_base: 9730c987a917621e35eb81f831747135dcafa382330112dd828b3673359780e7a3431309abd6d86083fa0bc19df32bd7a9f11b09e104a4889cb686950be5ba27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
